<?php
/**
 * Copyright © Mageleven (support@mageleven.com). All rights reserved.
 * Please visit Mageleven.com for license details (https://mageleven.com/end-user-license-agreement).
 */

/**
 * @var $block \Mageleven\HtmlSitemap\Block\Catalog\Category
 */
?>
<div class="sitemap-item-type sitemap-item-section">

    <?php $items = $block->getAllGroupedChildes(); ?>

    <?php if (count($items)) { ?>
        <div class="widget block block-categories" data-bind="scope: 'categories'">
            <div class="accordion"  id="accordion-2">
                <?php
                $level = 0;
                $first = true;
                foreach ($items as $item) {
                    $newLevel = $item->getLevel();
                    if ($level == $newLevel && !$first) {
                        echo '</li>';
                    }
                    if ($level < $newLevel) {
                        echo '<ul>';
                    }
                    if ($level > $newLevel) {
                        for ($i = $level; $i > $newLevel; $i--) {
                            echo '</ul></li>';
                        }
                    } ?>
                    <li>
                    <a href="<?= $block->escapeUrl($item->getUrl()) ?>" title="<?= $block->escapeHtml($item->getName()) ?>">
                        <?= $block->escapeHtml($item->getName()) ?>
                    </a>
                    <?php
                    $level = $newLevel;
                    $first = false;
                }

                $closedTags = ($level > 0) ? $level - 1 : 1;
                echo str_repeat('</li></ul>', $closedTags);
                ?>
            </div>
        </div>
    <?php } ?>
</div>


