<?php
/**
 * Copyright © Mageleven (support@mageleven.com). All rights reserved.
 * Please visit Mageleven.com for license details (https://mageleven.com/end-user-license-agreement).
 */

/**
 * @var $block \Mageleven\HtmlSitemap\Block\Additional\Additional
 */
?>
<?php
$links = $block->getAllLinksArray();
?>
<div class="sitemap-item-type sitemap-item-section">
    <?php if (count($links)): ?>

        <?php foreach ($links as $link): ?>
            <?php if ($link): ?>
                <a href="<?= $block->escapeUrl($block->getBaseUrl() . $link['url']) ?>" title="<?= $block->escapeHtml($link['title']) ?>">
                    <?= $block->escapeHtml($link['title'])?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
