<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright">
	        <div class="row">
	          <div class="col-lg-4">
	            <p>© Copyright 2020 by Mageleven. All Rights Reserved.</p>
	            <ul class="copylist">
	              <li><a href="#">Terms and conditions</a></li>
	              <li><a href="#">Privacy policy</a></li>
	              <li><a href="#">Refund policy</a></li>
	            </ul>
	          </div>
	          <div class="col-lg-8">
	            <ul class="tags">
	            	<li><a href="#">One Step Checkout</a></li>
	            	<li><a href="#">Layered Navigation Ultimate</a></li>
	            	<li><a href="#">Affiliate PRO</a></li>
	            	<li><a href="#">SEO All-in-one</a></li>
	            	<li><a href="#">Social Login</a></li>
	            	<li><a href="#">Better Blog</a></li>
	            	<li><a href="#">Security</a></li>
	            	<li><a href="#">Gift Card</a></li>
	            	<li><a href="#">Reward Points</a></li>
	            	<li><a href="#">Shop by Brand</a></li>
	            	<li><a href="#">SMTP</a></li>
	            	<li><a href="#">PDF Invoice</a></li>
	            	<li><a href="#">Avada Commerce</a></li>
	            	<li><a href="#">Avada Blog</a></li>
	            	<li><a href="#">Sitemap</a></li>
	            	<li><a href="#">Administration</a></li>
	            	<li><a href="#">Checkout</a></li>
	            	<li><a href="#">Promotions</a></li>
	            	<li><a href="#">B2B</a></li>
	            	<li><a href="#">Navigation</a></li>
	            	<li><a href="#">Product Enchancements</a></li>
	            	<li><a href="#">Sales Motivation</a></li>
	            	<li><a href="#">Content Management</a></li>
	            	<li><a href="#">User Experience</a></li>
	            	<li><a href="#">Order Management</a></li>
	            	<li><a href="#">SEO Suite</a></li>
	            	<li><a href="#">Payment</a></li>
	            	<li><a href="#">Extension Reviews</a></li>
	            </ul>
	          </div>
	        </div>
	    </div>
	</div>
</div>
<small class="copyright">
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
</small>
