<?php $helper = $this->helper('Itheavens\Fanpage\Helper\Data'); 
$currency_enable = $this->helper('Mageleven\AutoCurrency\Helper\Data');
?>

<header class="header wow fadeInDown sticky">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-2 col-md-3 col-sm-4"><?php echo $this->getChildHtml("logo"); ?>
             
            </div>
            <div class="col-xl-8 col-lg-10 col-md-9 col-sm-8 text-right">
                <span data-action="toggle-nav" class="action nav-toggle"><span>Toggle Nav</span></span>
                <div class="topbar">
                    <ul>
                        <?php if ($helper->customerSessionData()->isLoggedIn()) : ?>
                            <li><a href="<?= $this->getUrl("customer/account/logout"); ?>"><?= __("Logout"); ?></a></li>
                        <?php endif; ?>
                        <li>
                            <a class="search-toggle" href="#">
                                <svg class="svg-inline--fa fa-search fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                                    <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                                </svg>
                            </a>
                            <div id="topheadsearch" class="search-box">
                                <?= $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Search::form.mini.phtml')->toHtml(); ?>
                            </div>
                        </li>
                        <li><?php echo $this->getChildHtml("minicart"); ?></li>
                        <li><a href="<?php echo $this->getUrl("customer/account"); ?>"><svg class="svg-inline--fa fa-user fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="user" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 0c88.366 0 160 71.634 160 160s-71.634 160-160 160S96 248.366 96 160 167.634 0 256 0zm183.283 333.821l-71.313-17.828c-74.923 53.89-165.738 41.864-223.94 0l-71.313 17.828C29.981 344.505 0 382.903 0 426.955V464c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48v-37.045c0-44.052-29.981-82.45-72.717-93.134z"></path></svg></a></li>
                         <?php 
                         if($currency_enable->isEnabled() == 1){
                         if($helper->customerSessionData()->isLoggedIn()) {
                             echo $this->getLayout()->createBlock("Magento\Directory\Block\Currency")->setTemplate("Magento_Directory::currency.phtml")->toHtml(); 
                            }
                         }
                    ?>
                    </ul>
                </div>
                <?php echo $this->getChildHtml("navigation.sections"); ?>
            </div>
        </div>
    </div>
</header>

<?php if ($helper->getPagePath() == 'catalog_category_view') : ?>
<!-- banner -->
<section class="service-banner careers-banner ext-banner">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9 wow fadeInUp">
                <div class="slidcontent text-center">
                    <h4>“<?= __("Find extensions that can solve your business problems"); ?>”</h4>
                    <div class="search"><?= $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Search::form.mini.phtml')->toHtml(); ?></div>
                    <?= $block->getLayout()->createBlock('Magento\Search\Block\Term')->setTemplate('Magento_Search::term.phtml')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?php endif; ?>

<script>
require(['jquery'], function ($) {
    // Hide the search box initially
    //$('#topheadsearch').hide();

    // Toggle the search box when the search icon is clicked
    $('.search-toggle').click(function (e) {
        e.stopPropagation(); // Prevent the click event from propagating to the body
        $('#topheadsearch').toggle();
        $('#topheadsearch').toggleClass('walkers');
    });

    // Close the search box when clicking outside of it
    $('body').click(function () {
        $('#topheadsearch').hide();
        
    });

    // Prevent the search box from closing when clicking inside it
    $('#topheadsearch').click(function (e) {
        e.stopPropagation(); // Prevent the click event from propagating to the body
    });

    // To hide the search box when the page is loaded or refreshed
    $(document).ready(function () {
        $('#topheadsearch').hide();
    });

    setTimeout(function () {
        $(".loading-mask").addClass("lockmenow");
        $(".loading-mask").remove();
    }, 3000)

    $(".action.showcart").click(function () {
        $("#topheadsearch").css("display", "none");
    });

    /* for currency swithcer */
    $(".label.switcher-label").click(function(){
        $(".options.switcher-options").toggleClass("show_currency");
    })

    
});
</script>
