<?php
/**
 * @var Magezon\ScrollToTop\Block\Adminhtml\ $block
 */
$helper = $this->helper('\Magezon\ScrollToTop\Helper\Data');
?>

<style>
    .stt-button,
    .stt-icon,
    .stt-image {
        width: <?= $helper->getButttonSize() ?>px;
        height: <?= $helper->getButttonSize() ?>px;
    }
    .stt-button {
        <?= $helper->getStylePosition() ?>
    }

    .stt-text {
        background-color: <?= $helper->getBackGroundColor() ?>;
        color: <?= $helper->getTextColor() ?>;
        font-size: <?= $helper->getTextSize() ?>px;
    }

    .stt-icon {
        background-color: <?= $helper->getBackGroundColor() ?>;
        font-size: <?= $helper->getButttonSize() ?>px;
        color: <?= $helper->getIconColor() ?>;
    }
    
    @media (hover: hover) {
        .stt-button:hover .stt-icon {
            background-color: <?= $helper->getBackGroundHover() ?>;
            color: <?= $helper->getIconColorHover() ?>
        }
        .stt-button:hover .stt-text {
            background-color: <?= $helper->getBackGroundHover() ?>;
            color: <?= $helper->getTextColorHover() ?>;
        }
    }

    <?= $helper->getCustomCss() ?>
</style>

<div class="stt-button animate__animated" id="scroll-to-top">
    <?= $helper->getDisplayOnPage() ?>
</div>
