<?php
namespace Itheavens\Fanpage\Block\Index;
 
use Magento\Framework\View\Element\Template;
 
class Bundleaddtocart extends Template
{
  protected $request;
  protected $productCollection;
  protected $customerSession;
  protected $formKey;  
  protected $cart;
  protected $product;
  protected $response;
  private $redirectFactory;

  public function __construct(
      Template\Context $context, 
      \Magento\Framework\App\RequestInterface $request,
      \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection,
      \Magento\Customer\Model\Session $customerSession,
      \Magento\Framework\Data\Form\FormKey $formKey,
      \Magento\Checkout\Model\Cart $cart,
      \Magento\Catalog\Model\Product $product,
      \Magento\Framework\App\Response\Http $response,
      \Magento\Framework\Controller\Result\RedirectFactory $redirectFactory,
      array $data = []
    )
    {
        $this->request = $request;
        $this->productCollection = $productCollection;
        $this->customerSession = $customerSession;
        $this->formKey = $formKey;
        $this->cart = $cart;
        $this->product = $product;
        $this->response = $response;
        $this->redirectFactory = $redirectFactory;
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts()
  {
    $productIds = $this->customerSession->getMyIds();
    if (isset($productIds) ) {

            
        $this->cart->addProductsByIds($productIds);
        $this->cart->save();                
        
         $this->customerSession->unsMyIds();
        }
     
      $collections = $this->productCollection->addAttributeToSelect('*')->addFieldToFilter('entity_id',array('in' => $this->customerSession->getMyIds()));
     
     return $collections;
  }
}