<?php
namespace Itheavens\Fanpage\Block\Index;
 
use Magento\Framework\View\Element\Template;
 
class Bundleadded extends Template
{
  protected $request;
  protected $productCollection;
  protected $customerSession;

  public function __construct(
      Template\Context $context, 
      \Magento\Framework\App\RequestInterface $request,
      \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection,
      \Magento\Customer\Model\Session $customerSession,
      array $data = []
    )
    {
        $this->request = $request;
        $this->productCollection = $productCollection;
        $this->customerSession = $customerSession;
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts()
  {
    //$collections = [];
    //if(!empty($this->customerSession->getMyIds()) && isset($this->customerSession->getMyIds())){
      $collections = $this->productCollection->addAttributeToSelect('*')->addFieldToFilter('entity_id',array('in' => $this->customerSession->getMyIds()));
    //}
     return $collections;
  }
}