<?php
namespace Itheavens\Fanpage\Block\Index;
 
use Magento\Framework\View\Element\Template;
 
class Removebundle extends Template
{
  protected $request;
  protected $productCollection;
  protected $customerSession;

  public function __construct(
      Template\Context $context, 
      \Magento\Framework\App\RequestInterface $request,
      \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection,
      \Magento\Customer\Model\Session $customerSession,
      array $data = []
    )
    {
        $this->request = $request;
        $this->productCollection = $productCollection;
        $this->customerSession = $customerSession;
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts()
  {
     //$this->customerSession->setMyIds(array());
      $product_id = $this->request->getPostValue('product_id');
      $ids = $this->customerSession->getMyIds();

      if (($key = array_search($product_id, $ids)) !== false) {
          unset($ids[$key]);
      }
      
      $this->customerSession->setMyIds($ids);
      $collections = $this->productCollection->addAttributeToSelect('*')->addFieldToFilter('entity_id',array('in' => $this->customerSession->getMyIds()));
     return $collections;
  }
}