<?php
namespace Itheavens\Fanpage\Block\Index;
 
use Magento\Framework\View\Element\Template;
 
class View extends Template
{
  protected $request;
  protected $productCollection;
  public function __construct(
      Template\Context $context, 
      \Magento\Framework\App\RequestInterface $request,
      \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection,
      array $data = []
    )
    {
        $this->request = $request;
        $this->productCollection = $productCollection;
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts()
  {
      $edition = $this->request->getPostValue('edition');
      $search = ($this->request->getPostValue('search'))?$this->request->getPostValue('search'):'';
      $attribute_id = ($edition=='Enterprise')?213:216;
      $collections = $this->productCollection->addAttributeToSelect('*')->addAttributeToFilter('edition',$attribute_id);

      if($search){
        $collections = $collections->addAttributeToFilter('name',array('like' => '%' . $search . '%'));
      }

      //echo "<pre>"; print_r(get_class_methods($collections)); die;

     /*---------------ANY BUSINESS LOGIC---------*/
     return $collections;
  }
}