<!-- banner -->
<section class="service-banner">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-8 wow fadeInLeft">
				<div class="slidcontent">
					<h1>Bridging The Gap & Building Long-Term Relationships for Ecommerce Businesses</h1>
					<p>Explore Mageleven’s story to learn how our products create a story for your business too.</p>
					<a href="contact" class="btn btn-primary"><span>free your web-store</span> <i class="arrow"></i></a>
				</div>
			</div>
			<div class="col-lg-4 wow fadeInRight">
				<div class="bannerimg mt-0">
                <?php $imageUrl =  $this->getUrl() . 'media/cms/new/homebannernew.png';?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="homebannernew">
			   </div>
			</div>
		</div>
	</div>
</section>

<!-- We know 250+ ways of making your  -->
<section class="about-business wow fadeInUp">
	<div class="container">
		<h4 class="text-center">extensions</h4>
		<h2 class="text-center mb-3">Check how far Mageleven has come with +6K successful clients globally</h2>
		<div class="row">
			<div class="col-lg-12 text-center wow fadeInLeft">
				<?php $imageUrl = $this->getUrl() . 'media/cms/about.png'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="about">
				</div>
			<div class="col-lg-12 wow fadeInRight">
				
				<p class="pt-0">Mageleven is a leading Magento extension development company that serves ecommerce businesses all around the world. We came into the market with a vision to bridge the gap that ecommerce businesses are facing to build long-term relationships with their business customers and drive reliable technical aid. We want every online store to come up in the market by making a big impact on their targeted business customers.
We have served over 60K ecommerce businesses with our top and most used products of Magento 2 extensions. Our developed extension for Magento 2 comes with multiple benefits that ecommerce businesses are leveraging. These benefits include:</p>
<ul class="ul-style">
<li><strong>Improved customer experience: </strong> Our extensions help businesses improve the customer experience by providing them with a more convenient and user-friendly shopping experience.</li>
<li><strong>Increased sales: </strong> Our extensions help businesses increase sales by providing them with the tools they need to convert more visitors into customers.</li>
<li><strong>Reduced costs: </strong>  Our extensions help businesses to reduce costs by automating tasks and streamlining processes.</li>
<li><strong>Improved security: </strong>  Our extensions help businesses to improve security by protecting their data from unauthorized access.</li>
<ul>
<p>At Mageleven we make you believe that we will provide you with the best products and services. We are constantly innovating and developing new extensions that meet the needs of our customers. If you need any support we will be available 24/7, and you do not have to worry about the support you need. We have a team of experienced Magento developers who are available to help our customers with any questions or problems they may have.
We are confident that our products and services can help businesses to grow and succeed. We invite you to try our products and see how they can help you improve your business.</p>
			</div>
			<!-- <div class="col-lg-12 text-center">
				<a href="#" class="btn btn-primary">Pick mods you need</a>
			</div> -->
		</div>
	</div>
</section>

<!-- Make e-commerce better -->
<section class="make-ecom">
	<div class="container">
    	<div class="row align-items-center">
    		<div class="col-lg-6 text-center wow fadeInLeft">
                  <?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/make-ecom.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid mb-3" alt="Make e-commerce better">
    			</div>
    		<div class="col-lg-6 wow fadeInRight">
    			<h2 class="pt-0">What is making Mageleven the top choice for ecommerce businesses?</h2>
    			<p>Technology is for everyone, changing everyone’s life, and providing businesses with the top, reliable, and inexpensive solutions. Therefore, we want every ecommerce business to leverage the technology that makes their daily business practices easy, and effective, and makes their approach to the business customers simpler. After all, your business customer’s experience and satisfaction to buy from you matters most, right? So, to fulfill all these demands from every ecommerce business. Mageleven’s team has come up with the experience you need.</p>
    		</div>
    	</div>
	</div>
</section>

<!-- Full-service Magento Marketplace -->
<section class="marketplace wow fadeInUp">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center wow fadeInUp">
				<h2>Some of the reasons that make us stand out from others</h2>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="iconbox">
					<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/exp.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Experience">
					</div>
				<p>+10 Years Experience</p>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="iconbox">
					<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/cust.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Previous Customers">
					</div>
				<p>+6K Previous Customers</p>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="iconbox">
					<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/projects.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Projects Completed">
					</div>
				<p>+500 Projects Completed</p>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="iconbox">
					<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/review.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Support Team">
				</div>
				<p>24/7 Support Team</p>
			</div>
		</div>
	</div>
</section>

<!-- Offering Top Magento Services -->
<section class="offering wow fadeInUp">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center wow fadeInUp">
				<h2>Offering Top Magento Services</h2>
				<p>We boost your merchandising progress and help expend into unsurpassed competition.</p>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="whbox">
					<div class="iconbox">
                       <?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/ser1.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Partner Programs">
					</div>
					<div class="offcontent">
						<h3>Partner Programs</h3>
						<ul>
							<li>Analytics & Consultant</li>
							<li>Custom Theme Designing</li>
							<li>Magento Third Party Integrations</li>
							<li>Performance Optimization</li>
							<li>Technical Support</li>
							<li>Magento SEO</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="whbox">
					<div class="iconbox">
						<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/ser2.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Magento Maintenance">
						</div>
					<div class="offcontent">
						<h3>Magento Maintenance</h3>
						<ul>
							<li>Security Patches</li>
							<li>Version Upgrades</li>
							<li>Site Audit</li>
							<li>Performance Management</li>
							<li>Monitoring/Alerts</li>
							<li>Clean/Roll-up Logs</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="whbox">
					<div class="iconbox">
						<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/ser3.jpg'; ?>
                    		<img src="<?= $imageUrl ?>" class="img-fluid" alt="Magento 2 Migration">
						
					</div>
					<div class="offcontent">
						<h3>Magento 2 Migration</h3>
						<ul>
							<li>Theme migration</li>
							<li>Extension migration</li>
							<li>Custom code migration</li>
							<li>Data migration</li>
							<li>Performance optimisation</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 wow fadeInUp">
				<div class="whbox">
					<div class="iconbox">
						<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/ser4.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="B2B Implementation">
					</div>
					<div class="offcontent">
						<h3>B2B Implementation</h3>
						<ul>
							<li>Custom quote and ordering processes</li>
							<li>Complex product and shipping setup</li>
							<li>B2B storefront management</li>
							<li>Custom pricing / exemption features</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Customer's Satisfaction - Top Priority -->
<section class="satisfaction wow fadeInUp">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-10">
				<h2>Our values</h2>
				<p>At Mageleven, we believe that values are the foundation of a successful organization. They shape the character of the company and determine how it interacts with its customers, employees, and community. We believe in the values that we deliver to our customers, no matter where they are located.
We believe that our values are what make us a trusted and respected partner. We are committed to providing our customers with the highest quality products and services, and we always strive to exceed their expectations. We believe that our values are what make us a great place to work. Mageleven offers a positive and supportive work environment, and we are committed to providing our employees with the resources they need to succeed. We believe that our values are what make us responsible members of the community. Mageleven is committed to giving back to the communities in which we operate, and we believe that we have a responsibility to make a positive impact on the world.
We believe that our values are what make Mageleven a unique and special company. We are proud of the values that we live by, and we are committed to continuing to uphold them in the years to come.</p>
				<?php $imageUrl = $block->getBaseUrl() . 'static/frontend/Mageleven/m2-theme/en_US/img/toprating.jpg'; ?>
                    <img src="<?= $imageUrl ?>" class="img-fluid" alt="Our values">
			</div>
		</div>
	</div>
</section>

<!-- happy client -->
<!-- <div class="happyclient wow fadeInUp">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8">
				<h2><? // echo__('Our Happy Clients'); ?></h2>
				<div class="clientbox">
					<?php //echo $this->getLayout()->createBlock("Magiccart\Testimonial\Block\Post\TestimonialList")->setTemplate("post/listAbout.phtml")->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div> -->