<section class="service-banner">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-banner')->toHtml(); ?>
</section>
<section>
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-welcome-message')->toHtml(); ?>
</section>
<section class="whyus wow fadeInUp">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-why-us')->toHtml(); ?>
</section>
<section class="writeabout wow fadeInUp">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-write-about')->toHtml(); ?>
</section>
<!-- <section class="blogcat wow fadeInUp">
   <div class="container">
      <div class="row">
         <?php// echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-blog-categories')->toHtml(); ?>
      </div>
   </div>
</section> -->
<!-- Who is our audience? -->
<!-- <section class="container wow fadeInUp">
   <div class="audience">
      <div class="row justify-content-center">
         <div class="col-lg-9">
            <?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-audience')->toHtml(); ?>
         </div>
      </div>
   </div>
</section> -->
<section class="container wow fadeInUp">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-why-contribute')->toHtml(); ?>
</section>
<!-- <section class="wexpect wow fadeInUp">
   <div class="container">
      <div class="row">
         <div class="col-lg-12">
            <?php// echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-expect')->toHtml(); ?>
         </div>
      </div>
   </div>
</section>
<section class="nowith wow fadeInUp">
   <div class="container">
      <div class="row">
         <?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-no-with')->toHtml(); ?>
      </div>
   </div>
</section> -->
<section class="editorial wow fadeInUp row-sec-just">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contributor-editorial-process')->toHtml(); ?>
</section>


<!-- Blog contribution request -->
<div class="blogrequest wow fadeInUp">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12 text-center">
        <h2>Blog contribution request</h2>
        <h5>Please fill out the form to submit your content. We will contact to you as soon as possible.</h5>
      </div>
      <div class="col-lg-10">
        <div class="formbox">
           <form class="form contact" action="<?php  echo $this->getUrl('contributors/index/save', ['_secure' => true]);?>" id="custom-form" method="post" data-hasrequired="<?php   echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}' style="width:100%; float: none;" >
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" name="author_name" class="form-control" placeholder="Author's name" required data-validate="{required:true}" />
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Company" name="company" data-validate="{required:true}"/>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Website" name="website" data-validate="{required:true}"/>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Email" name="email"  required data-validate="{required:true, 'validate-email':true}" />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Why do you want to contribute to our blog?" name="blog_contribute" data-validate="{required:true}" />
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <select class="form-control" name="dev_doc" data-validate="{required:true}">
                    <option value="Magento dev-docs">Magento dev-docs</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Your content on Google docs" name="google_docs_content" data-validate="{required:true}"/>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Note" name="note" data-validate="{required:true}"/>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 text-center">
                  <button type="submit" title="<?php  echo __('Submit') ?>" class="btn btn-primary" id="custom_btn">
                    <span><?php  echo __('Submit') ?></span>
                  </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script>require(['jquery','mageplaza/core/bootstrap'],function() {});</script>
<script>
  require([
    'jquery',
    'mage/validation'
], function ($)
 {
    $.validator.addMethod(
        'validate-custom-phone', 
        function (value, element) {
            // Check if the value matches the allowed format and has a maximum length of 10 digits
            return this.optional(element) || /^[0-9 ()+-]{10}$/.test(value);
        }, 
        $.mage.__('Please enter a valid 10-digit phone number.')
    );

    $('#custom-form').mage('validation', {});

});
</script>