<!-- banner -->
   <section class="service-banner careers-banner ext-banner">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9 wow fadeInUp">
                <div class="slidcontent text-center">
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <h4>“Get Mageleven’s Solutions in The Extension Form”</h4>
                        </div>
                        <div class="col-md-6">
                            <!-- <form class="form contact" method="get" style="width: 100%;"> -->
                                <div class="search form contacts" style="width: 100%;">
                                    <div id="topheadsearchs" class="search-boxsss">
                                        <?= $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Search::form.mini.phtml')->toHtml(); ?>
                    <?php  //$block->getLayout()->createBlock('Magento\Search\Block\Term')->setTemplate('Magento_Search::term.phtml')->toHtml(); ?>
                                        
                                    </div>
                                </div>
                            <!-- </form> -->
                        </div>
                    </div>
    					<!-- <ul>
    						<li>Accurate Products Search</li>
    						<li>Cost-Effective Delivery</li>
    						<li>Fast & Easy Store Control </li>
    						<li>Higher Positions in Google </li>
    						<li>Accurate Products Search</li>
    						<li>Cost-Effective Delivery</li>
    						<li>Fast & Easy Store Control </li>
    						<li>Higher Positions in Google </li>
    					</ul> -->
    				</div>
    			</div>
    		</div>
    	</div>
    </section>

    <!-- New Magento 2 Extensions -->
    <section class="newextension m2ext loc">
    	<div class="container">
    		<div class="row">
    			<div class="col-lg-12 wow fadeInDown">
    				<h2>Magento 2 Extensions</h2>
    			</div>
    			<?php 
    				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    				$helper_data = $this->helper('\Itheavens\Fanpage\Helper\Data');
    				$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
    				$collection = $helper_data->getExtensionList();
					if(@$_GET['search']){
				    	$search = $_GET['search'];
				    	$collection = $collection->addAttributeToFilter('name', array('like' => '%'.$search.'%'));
				    } 
					$collection = $collection->setPageSize(8)->load();

					foreach ($collection as $product){
							$productId = $product->getId();
							
							$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
							$product_data = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
							$storeManager  = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
							$storeId = $storeManager->getStore()->getStoreId();
							$reviewFactory->getEntitySummary($product_data, $storeId);

							$ratingSummary = $product_data->getRatingSummary()->getRatingSummary();
							$reviewCount = $product_data->getRatingSummary()->getReviewsCount();
							$helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');
					    	$imageUrl = $helperImport->init($product, 'product_page_image_small')
                ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
                ->resize(380)
                ->getUrl();
    			?>
    			<div class="col-lg-3 col-md-6 wow fadeInUp">
    				<div class="solbox smartway">
    					<div class="imgbox"><a href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo $imageUrl; ?>" class="img-fluid" alt="Brick by Brick"></a></div>
    					<h3><a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a></h3>

    					<div class="price">
                            <?php echo ($product->getFinalPrice() == 0 ? 'Free' :  $priceHelper->currency($product->getFinalPrice(), true, false))  ?>
                            <?php //echo $priceHelper->currency($product->getFinalPrice(), true, false); ?>
                                

                            </div>
    					<div class="review"><?php echo (isset($reviewCount) ? $reviewCount : 0 ); ?> reviews</div>
    					<div class="clearfix"></div>
    				</div>
    			</div>
    			<?php } ?>
    			
    		</div>
    	</div>
    </section>



 
<div class="container">
	<div class="urseexp gray-bg-box0">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extensions-experience')->toHtml(); ?>
	</div>
</div>

<div class="essential">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extensions-essential')->toHtml(); ?>
</div>
<div class="solutionpkg">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extensions-solution')->toHtml(); ?>
</div>
<!-- conclusion -->
<div class="container">
   <!-- <div class="conclusion"> -->
   		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('extensions-conclusion')->toHtml(); ?> 
     
 <!--  </div> -->
</div>