<section class="about-business service-page-sec">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-5 order-lg-last">
         <img src="<?php echo $this->getUrl('media/cms/new')."business-img.png"; ?>" alt="business-img">
        </div>
        <div class="col-lg-7">
          <h2 class="service-psec-title fw-700">Beyond Development: Elevate Your Magento Journey with Mageleven</h2>
          <p class="small-p mb-4">This emphasizes development and a holistic partnership for a successful Magento journey.</p>

          <!-- Search Box Start -->
         <!--  <div class="search-box" style="max-width:365px;">
            <form>
              <input type="text" name="search" class="form-control" placeholder="Search here..." id="searchblog">
              <button class="search-btn" type="submit" id="button-addon2">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
          </div> -->
          <!-- Search Box End -->
          <!-- new search Box -->
          <div class="search-box">
          <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Search::form.mini.phtml")->toHtml();?>
          </div>
          <!-- search box end -->

        </div>
      </div>
  
    </div>
  </section>

  <section class="new-partners-sec wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
    <div class="container">
      <div class="section-title">Mageleven's Network of Excellence: Trustworthy Partners Fueling Growth</div>

      <div class="agency-list-title">Partner Agencies</div>

      <div class="row justify-content-center">
        <!-- Col Start -->
        <div class="col-xl-8 col-lg-9">
          <div class="row justify-content-center">
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img.png"; ?>" alt="client-img">              
                </div>
                <div class="new-partners-list-title">MageXpert</div>
                <p>Agile Architects, Crafting Powerful Magento Experiences</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                <img src="<?php echo $this->getUrl('media/cms/new')."client-img2.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">Conversion Craft</div>
                <p>Creative Catalysts, Turning Browsers into Buyerse</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                 <img src="<?php echo $this->getUrl('media/cms/new')."client-img3.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">EcomGreen</div>
                <p>Building Sustainable Brands, One Store at a Time</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                 <img src="<?php echo $this->getUrl('media/cms/new')."client-img4.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">DataHawk</div>
                <p>Metrics Masters, Unlocking Magento's Hidden Potential</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img5.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">WorldShipper</div>
                <p>Borderless Fulfillment, Delivering Global Success</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                <img src="<?php echo $this->getUrl('media/cms/new')."client-img6.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">FortifyX</div>
                <p>Trust Architects, Securing Your Ecommerce Ecosystem</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
             <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                   <img src="<?php echo $this->getUrl('media/cms/new')."client-img.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">MageCloud</div>
                <p>Extension Experts, Supercharging Your Magento Store</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
             <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img2.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">Marketing Mojo</div>
                <p>Conversion Whisperers, Igniting Magento Growth</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
             <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img3.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">SEO Alchemy</div>
                <p>Search Sorcerers, Making Your Magento Shine</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
            <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img4.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">Customer Centric</div>
                <p>Experience Alchemists, Crafting Magento Joy</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
                <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img5.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">FinTech Forge</div>
                <p>Payment Pioneers, Streamlining Your Magento Flow</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
          <!-- Col Start -->
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="new-partners-list">
                <div class="new-partners-img">
                  <img src="<?php echo $this->getUrl('media/cms/new')."client-img6.png"; ?>" alt="client-img"> 
                </div>
                <div class="new-partners-list-title">Content Craft</div>
                <p>Storytellers in Code, Weaving Magento Magic</p>
                <a href="#" class="partner-web-link">Partner website</a>
              </div>
            </div>
            <!-- Col End -->
      
      
          </div>

          <nav aria-label="Page navigation example">
            <ul class="pagination pagination-design justify-content-center">
              <li class="page-item disabled">
                <a class="page-link pre-link" href="#" tabindex="-1"><img src="<?php echo $this->getUrl('media/cms/new')."pre-page-icon.png"; ?>" alt="pre-page-icon"></a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link next-link" href="#"><img src="<?php echo $this->getUrl('media/cms/new')."next-page-icon.png"; ?>" alt="next-page-icon"></a>
              </li>
            </ul>
          </nav>

        </div>
        <div class="col-xl-4 col-lg-3">

          <div class="countries-box">
            <div class="countries-box-title">All Countries</div>
            <div class="countries-box-inner">
              <div class="country-name">Afghanistan</div>
              <div class="country-name">Albania</div>
              <div class="country-name">Algeria</div>
              <div class="country-name">Andorra</div>
              <div class="country-name">Angola</div>
              <div class="country-name">Antigua and Barbuda</div>
              <div class="country-name">Argentina</div>
              <div class="country-name">Armenia</div>
              <div class="country-name">Australia</div>
              <div class="country-name">Austria</div>
              <div class="country-name">Azerbaijan</div>
              <div class="country-name">The Bahamas</div>
              <div class="country-name">Bahrain</div>
              <div class="country-name">Bangladesh</div>
              <div class="country-name">Barbados</div>
              <div class="country-name">Belarus</div>
              <div class="country-name">Belgium</div>
              <div class="country-name">Belize</div>
              <div class="country-name">Benin</div>
              <div class="country-name">Bhutan</div>
              <div class="country-name">Bolivia</div>
              <div class="country-name">Bosnia and Herzegovina</div>
              <div class="country-name">Botswana</div>
              <div class="country-name">Brazil</div>
              <div class="country-name">Brunei</div>
              <div class="country-name">Bulgaria</div>
              <div class="country-name">Burkina Faso</div>
              <div class="country-name">Burundi</div>
              <div class="country-name">Cabo Verde</div>
              <div class="country-name">Cambodia</div>
              <div class="country-name">Cameroon</div>
              <div class="country-name">Canada</div>
              <div class="country-name">Central African Republic</div>
              <div class="country-name">Chad</div>
              <div class="country-name">Chile</div>
              <div class="country-name">China</div>
              <div class="country-name">Colombia</div>
              <div class="country-name">Comoros</div>
              <div class="country-name">Congo, Democratic Republic of the</div>
              <div class="country-name">Congo, Republic of the</div>
              <div class="country-name">Costa Rica</div>
              <div class="country-name">Côte d’Ivoire</div>
              <div class="country-name">Croatia</div>
              <div class="country-name">Cuba</div>
              <div class="country-name">Cyprus</div>
              <div class="country-name">Czech Republic</div>
              <div class="country-name">Denmark</div>
              <div class="country-name">Djibouti</div>
              <div class="country-name">Dominica</div>
              <div class="country-name">Dominican Republic</div>
              <div class="country-name">East Timor (Timor-Leste)</div>
              <div class="country-name">Ecuador</div>
              <div class="country-name">Egypt</div>
              <div class="country-name">El Salvador</div>
              <div class="country-name">Equatorial Guinea</div>
              <div class="country-name">Eritrea</div>
              <div class="country-name">Estonia</div>
              <div class="country-name">Eswatini</div>
              <div class="country-name">Ethiopia</div>
              <div class="country-name">Fiji</div>
              <div class="country-name">Finland</div>
              <div class="country-name">France</div>
              <div class="country-name">Gabon</div>
              <div class="country-name">The Gambia</div>
              <div class="country-name">Georgia</div>
              <div class="country-name">Germany</div>
              <div class="country-name">Ghana</div>
              <div class="country-name">Greece</div>
              <div class="country-name">Grenada</div>
              <div class="country-name">Guatemala</div>
              <div class="country-name">Guinea</div>
              <div class="country-name">Guinea-Bissau</div>
              <div class="country-name">Guyana</div>
              <div class="country-name">Haiti</div>
              <div class="country-name">Honduras</div>
              <div class="country-name">Hungary</div>
              <div class="country-name">Iceland</div>
              <div class="country-name">India</div>
              <div class="country-name">Indonesia</div>
              <div class="country-name">Iran</div>
              <div class="country-name">Iraq</div>
              <div class="country-name">Ireland</div>
              <div class="country-name">Israel</div>
              <div class="country-name">Italy</div>
              <div class="country-name">Jamaica</div>
              <div class="country-name">Japan</div>
              <div class="country-name">Jordan</div>
              <div class="country-name">Kazakhstan</div>
              <div class="country-name">Kenya</div>
              <div class="country-name">Kiribati</div>
              <div class="country-name">Korea, North</div>
              <div class="country-name">Korea, South</div>
              <div class="country-name">Kosovo</div>
              <div class="country-name">Kuwait</div>
              <div class="country-name">Kyrgyzstan</div>
              <div class="country-name">Laos</div>
              <div class="country-name">Latvia</div>
              <div class="country-name">Lebanon</div>
              <div class="country-name">Lesotho</div>
              <div class="country-name">Liberia</div>
              <div class="country-name">Libya</div>
              <div class="country-name">Liechtenstein</div>
              <div class="country-name">Lithuania</div>
              <div class="country-name">Luxembourg</div>
              <div class="country-name">Madagascar</div>
              <div class="country-name">Malawi</div>
              <div class="country-name">Malaysia</div>
              <div class="country-name">Maldives</div>
              <div class="country-name">Mali</div>
              <div class="country-name">Malta</div>
              <div class="country-name">Marshall Islands</div>
              <div class="country-name">Mauritania</div>
              <div class="country-name">Mauritius</div>
              <div class="country-name">Mexico</div>
              <div class="country-name">Micronesia, Federated States of</div>
              <div class="country-name">Moldova</div>
              <div class="country-name">Monaco</div>
              <div class="country-name">Mongolia</div>
              <div class="country-name">Montenegro</div>
              <div class="country-name">Morocco</div>
              <div class="country-name">Mozambique</div>
              <div class="country-name">Myanmar (Burma)</div>
              <div class="country-name">Namibia</div>
              <div class="country-name">Nauru</div>
              <div class="country-name">Nepal</div>
              <div class="country-name">Netherlands</div>
              <div class="country-name">New Zealand</div>
              <div class="country-name">Nicaragua</div>
              <div class="country-name">Niger</div>
              <div class="country-name">Nigeria</div>
              <div class="country-name">North Macedonia</div>
              <div class="country-name">Norway</div>
              <div class="country-name">Oman</div>
              <div class="country-name">Pakistan</div>
              <div class="country-name">Palau</div>
              <div class="country-name">Panama</div>
              <div class="country-name">Papua New Guinea</div>
              <div class="country-name">Paraguay</div>
              <div class="country-name">Peru</div>
              <div class="country-name">Philippines</div>
              <div class="country-name">Poland</div>
              <div class="country-name">Portugal</div>
              <div class="country-name">Qatar</div>
              <div class="country-name">Romania</div>
              <div class="country-name">Russia</div>
              <div class="country-name">Rwanda</div>
              <div class="country-name">Saint Kitts and Nevis</div>
              <div class="country-name">Saint Lucia</div>
              <div class="country-name">Saint Vincent and the Grenadines</div>
              <div class="country-name">Samoa</div>
              <div class="country-name">San Marino</div>
              <div class="country-name">Sao Tome and Principe</div>
              <div class="country-name">Saudi Arabia</div>
              <div class="country-name">Senegal</div>
              <div class="country-name">Serbia</div>
              <div class="country-name">Seychelles</div>
              <div class="country-name">Sierra Leone</div>
              <div class="country-name">Singapore</div>
              <div class="country-name">Slovakia</div>
              <div class="country-name">Slovenia</div>
              <div class="country-name">Solomon Islands</div>
              <div class="country-name">Somalia</div>
              <div class="country-name">South Africa</div>
              <div class="country-name">Spain</div>
              <div class="country-name">Sri Lanka</div>
              <div class="country-name">Sudan</div>
              <div class="country-name">Sudan, South</div>
              <div class="country-name">Suriname</div>
              <div class="country-name">Sweden</div>
              <div class="country-name">Switzerland</div>
              <div class="country-name">Syria</div>
              <div class="country-name">Taiwan</div>
              <div class="country-name">Tajikistan</div>
              <div class="country-name">Tanzania</div>
              <div class="country-name">Thailand</div>
              <div class="country-name">Togo</div>
              <div class="country-name">Tonga</div>
              <div class="country-name">Trinidad and Tobago</div>
              <div class="country-name">Tunisia</div>
              <div class="country-name">Turkey</div>
              <div class="country-name">Turkmenistan</div>
              <div class="country-name">Tuvalu</div>
              <div class="country-name">Uganda</div>
              <div class="country-name">Ukraine</div>
              <div class="country-name">United Arab Emirates</div>
              <div class="country-name">United Kingdom</div>
              <div class="country-name">United States</div>
              <div class="country-name">Uruguay</div>
              <div class="country-name">Uzbekistan</div>
              <div class="country-name">Vanuatu</div>
              <div class="country-name">Vatican City</div>
              <div class="country-name">Venezuela</div>
              <div class="country-name">Vietnam</div>
              <div class="country-name">Yemen</div>
              <div class="country-name">Zambia</div>
              <div class="country-name">Zimbabwe</div>
            </div>
          </div>
          
        </div>
      </div>
  
    </div>
  </section>


  <div class="vip-customer web-design-company">
    <div class="container">
      <div class="section-title">Why Mageleven Stands Out: Your Triple Win Partnership</div>

      <div class="row justify-content-center">

        <!-- Col Start -->
        <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
          <div class="vip-customer-list">
            <div class="vip-customer-icon">
              <img src="<?php echo $this->getUrl('media/cms/new')."slack-icon.png"; ?>" alt="slack-icon">
            </div>
            <div class="vip-customer-title">Expert Ecosystem</div>
            <p>Leverage the combined power of leading agencies, tailored to your unique needs. With our network of trusted partners, we can provide you with the best possible service and support. We will work with you to understand your specific requirements and then match you with the right agencies to meet your needs. We will also provide ongoing support to ensure that you are getting the most out of your partnership.</p>
          </div>
        </div>
        <!-- Col End -->
        
        <!-- Col Start -->
        <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
          <div class="vip-customer-list">
            <div class="vip-customer-icon">
             <img src="<?php echo $this->getUrl('media/cms/new')."personal-support.png"; ?>" alt="personal-support">
            </div>
            <div class="vip-customer-title">Streamlined Success</div>
            <p>With Mageleven as your central point of contact, you can enjoy seamless collaboration. All of your team members can access the same information and updates, and they can easily communicate with each other. This makes it easy to stay on the same page and get projects done on time.</p>
          </div>
        </div>
        <!-- Col End -->
        
        <!-- Col Start -->
        <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
          <div class="vip-customer-list">
            <div class="vip-customer-icon">
             <img src="<?php echo $this->getUrl('media/cms/new')."fast-forward.png"; ?>" alt="fast-forward">
            </div>
            <div class="vip-customer-title">Future-Proof Growth</div>
            <p>Magento is a leading open-source eCommerce platform that is well-suited for businesses of all sizes. It is flexible, scalable, and secure. You get a rich experience with the reliable services you need for your online store.</p>
          </div>
        </div>
        <!-- Col End -->

      </div>

    </div>
  </div>

</div>
  </div>
