<div class="help-desk-banner">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xxl-5 col-xl-6 col-lg-5 col-md-6 col-sm-6">
          <div class="deal-banner-inner">
            <div class="help-desk-sub">Help Desk</div>
            <div class="help-desk-title">Your Tech Allies</div>
            <div class="help-desk-sort">Unwavering Mageleven Support</div>

            <ul class="star-ul">
              <li>Expert guidance is always at hand.</li>
              <li>Resolving issues with speed and precision.</li>
              <li>Your success is our top priority.</li>
            </ul>
            
          </div>
        </div>
        <div class="col-xxl-7 col-xl-6 col-lg-7 col-md-6 col-sm-6 text-right">
          <img src="<?php echo $this->getUrl('media/cms/new')."help-desk-img.png"; ?>" alt="help-desk">
        </div>
      </div>
    </div>
  </div>

  <div class="our-availability text-center">
    <div class="container">
      <div class="section-sub">Extended Coverage for Your Peace of Mind</div>
      <div class="section-stitle">Customer-Centric to the Core: Achieving Customer Excellence</div>
      <div class="section-sort">Check Mageleven Team’s Availability</div>

      <ul class="nav justify-content-center nav-pills primary-tab" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link standtimes" id="ict-tab" data-toggle="tab" href="#ict" role="tab" aria-controls="ict" aria-selected="false">ICT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active standtime" id="utc-tab" data-toggle="tab" href="#utc" role="tab" aria-controls="utc" aria-selected="true">UTC</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">

        <div class="tab-pane fade" id="ict" role="tabpanel" aria-labelledby="ict-tab">
          <ul class="avail-ul">
            <li>8:00 - 24:00 ICT Monday to Friday</li>
            <li>8:00 - 12:00 ICT on Saturday</li>
          </ul>
        </div>

        <div class="tab-pane fade" id="utc" role="tabpanel" aria-labelledby="utc-tab">
          <ul class="avail-ul">
            <li>8:00 - 24:00 ICT Monday to Friday</li>
            <li>8:00 - 11:00 ICT on Saturday</li>
          </ul>
        </div>

      </div>
  

      <img src="<?php echo $this->getUrl('media/cms/new')."maintenance-service-img.png"; ?>" alt="maintenance-service">
      <div class="online-title">Preferred Treatment for <span>Our Most</span> Important Partners</div>

      <div class="customer-time-box">

        <div class="customer-time-list">
          <big id="seconds-demo"></big>
          <span>Second</span>
        </div>
        <div class="customer-time-list">
          <big id="minutes-demo"></big>
          <span>Minuets</span>
        </div>
        <div class="customer-time-list">
          <big id="hours-demo"></big>
          <span>Hours</span>
        </div>
        <!-- <div class="customer-time-list">
          <big id="day-demo"></big>
          <span>Day</span>
        </div> -->
        <div class="customer-time-list pm-text">
          <big>PM</big>
        </div>
      </div>

      <div class="vip-customer">
        <div class="vip-customer-toptitle">Preferred Treatment for Our Most Important Partners</div>

        <div class="row justify-content-center">

          <!-- Col Start -->
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="vip-customer-list">
              <div class="vip-customer-icon">
                <img src="<?php echo $this->getUrl('media/cms/new')."slack-icon.png"; ?>" alt="slack-icon">
              </div>
              <div class="vip-customer-title">Dedicated account manager for personalized support</div>
              <p>This means that you will have a single point of contact who will be responsible for your account and will be available to answer your questions and help you resolve any issues.</p>
            </div>
          </div>
          <!-- Col End -->
          
          <!-- Col Start -->
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="vip-customer-list">
              <div class="vip-customer-icon">
                <img src="<?php echo $this->getUrl('media/cms/new')."personal-support.png"; ?>" alt="personal-support">
              </div>
              <div class="vip-customer-title">Priority response times for urgent issues</div>
              <p>This means that you will receive a faster response to your requests when they are urgent.</p>
            </div>
          </div>
          <!-- Col End -->
          
          <!-- Col Start -->
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="vip-customer-list">
              <div class="vip-customer-icon">
                <img src="<?php echo $this->getUrl('media/cms/new')."fast-forward.png"; ?>" alt="fast-forward">
              </div>
              <div class="vip-customer-title">Exclusive access to advanced resources and expertise</div>
              <p>This means that you will have access to resources and expertise that are not available to the general public.</p>
            </div>
          </div>
          <!-- Col End -->

        </div>

      </div>

      <div class="reach-out-section">
        <div class="section-title">Getting the Help You Need</div>

            <div class="row justify-content-between align-items-center reach-out-row">
              <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 order-sm-last">
                <img src="<?php echo $this->getUrl('media/cms/new')."help-center.png"; ?>" alt="help-center">
              </div>
              <div class="col-xl-5 col-lg-5 col-md-7 col-sm-7">
                <div class="reach-out-title">Effortless Access to Solutions</div>
                <p>Connect with our team of experts through multiple convenient channels:</p>
                <ul>
                  <li><strong>Phone:</strong> Reach us directly for immediate assistance. </li>
                  <li><strong>Live Chat:</strong> Engage in real-time conversations with our support specialists. </li>
                  <li><strong>Ticketing System:</strong> Submit detailed requests for thorough resolution. </li>
                  <li><strong>Knowledge Base:</strong> Explore a comprehensive library of self-help resources. </li>
                </ul>
                <a href="#" class="btn btn-primary fn-sm">FIND SOLUTIONS</a>
              </div>
            </div>

            <div class="row justify-content-between align-items-center reach-out-row">
              <div class="col-xl-5 col-lg-5 col-md-5  col-sm-5">
                <img src="<?php echo $this->getUrl('media/cms/new')."help-desk-img.png"; ?>" alt="help-desk">
              </div>
              <div class="col-xl-5 col-lg-5 col-md-7 col-sm-7">
                <div class="reach-out-title">Values That Drive Exceptional Support</div>
                <p>We uphold the unwavering commitment to:</p>
                   <ul>
                  <li><strong>Responsiveness:</strong> Addressing your needs promptly and efficiently.</li>
                  <li><strong> Expertise:</strong> Delivering solutions with deep knowledge and understanding.</li>
                  <li><strong>Partnership:</strong> Collaborating for long-term success, not just quick fixes. </li>
                </ul>
                <a href="#" class="btn btn-primary fn-sm">NEW TICKET</a>
              </div>
            </div>

      </div>


    </div>
  </div>


  <div class="maint-services">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        <div class="col-xl-7 col-lg-6 col-md-6 col-sm-5 order-sm-last">
         <img src="<?php echo $this->getUrl('media/cms/new')."maintenance-img.png"; ?>" alt="maintenance-img">
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-7">
          <div class="maint-services-title">The Mageleven Difference</div>
          <p>We go beyond basic support to provide:</p>
          <ul class="star-ul">
           <li> Proactive problem prevention </li>
           <li>Strategic guidance for growth </li>
           <li> Unwavering commitment to your success </li>
          </ul>
          <a href="#" class="btn fn-sm btn-borderedW">GET STARTED</a>
        </div>
      </div>
    </div>
  </div>

  <section class="faq-section">
    <div class="container">
        <div class="section-title">Frequently Ask Questions</div>
        <div class="faq-questions">
      <!-- Question 1 -->
    <div class="faq-item">
        <div class="question"><span>How can I access Mageleven support?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
        <div class="answer" style="display: none;"><p>You can reach our friendly support team through multiple channels:
</p>
<ul class="check-ul">
<li><strong>Phone:</strong> Call us directly at [your phone number] for immediate assistance.</li>
<li><strong>Live Chat:</strong> Click the "Chat with Us" button on our website to connect with a support specialist in real-time </li>
<li><strong>Ticketing System:</strong> Submit a detailed request through our online ticketing system at [your website address] for thorough resolution.</li>
<li><strong>Knowledge Base:</strong> Browse our comprehensive library of self-help articles and tutorials at [your website address] to find answers to common questions.</li>
</ul>
</div>
    </div>

        <!-- Question 2 -->
        <div class="faq-item">
            <div class="question"><span>What are your support hours?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
            <div class="answer" style="display: none;"><p>Our support team is available 24/7 to ensure you receive the help you need whenever you need it.</p></div>
        </div>

         <!-- Question 3 -->
        <div class="faq-item">
            <div class="question"><span>What types of issues do you assist with?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
            <div class="answer" style="display: none;"><p>We provide expert support for a wide range of issues, including:</p>
              <ul class="check-ul">
                <li>Magento migration and upgrade challenges </li>
                <li>Technical troubleshooting and error resolution  </li>
                <li>Performance optimization and website maintenance  </li>
                <li>Security threats and data protection inquiries  </li>
                <li>Custom development and plugin integration assistance </li>
              </ul>

            </div>
        </div>

         <!-- Question 4 -->
        <div class="faq-item">
            <div class="question"><span>What are the benefits of being a VIP customer?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
            <div class="answer" style="display: none;"><p>As a VIP customer, you enjoy exclusive benefits such as:</p>
              <ul class="check-ul">
                <li>Dedicated account manager for personalized support and proactive problem prevention. </li>
                <li>Priority response times for urgent issues, minimizing downtime, and maximizing efficiency.  </li>
                <li>Exclusive access to advanced resources and expertise, ensures you receive the best possible solutions.  </li>
              </ul>
            </div>
        </div>

         <!-- Question 5 -->
        <div class="faq-item">
            <div class="question"><span> What if I have a complex issue that requires specialized expertise?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
            <div class="answer" style="display: none;"><p>We have a network of highly skilled developers and Magento experts on hand to tackle even the most complex challenges. If your issue goes beyond the scope of our standard support, we will connect you with the right specialist to ensure a seamless and effective resolution.</p></div>
        </div>

         <!-- Question 6 -->
        <div class="faq-item">
            <div class="question"><span>How can I provide feedback on my support experience?</span><span class="toggle"><svg id="Layer_1" style="enable-background:new 0 0 50 50;" version="1.1" viewBox="0 0 50 50" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1_1_"><polygon points="48.707,13.853 47.293,12.44 25,34.732 2.707,12.44 1.293,13.853 25,37.56  "></polygon></g></svg></span></div>
            <div class="answer" style="display: none;"><p>We value your feedback and always strive to improve. You can share your thoughts through our online survey, live chat conversations, or email us directly at [your email address]. We appreciate your input and use it to continually enhance our services and ensure your complete satisfaction.</p></div>
        </div>

</div>
       
    </div>
  </section>


  <section class="contact-form-sec">
    <div class="container">
      <div class="contact-form-title">Want to build a Magento website that</div>
      <p class="intro">Has the right features. Hits the right goal. At a remarkably affordable price. Contact us!</p>

      <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-10">
          <form action="<?php echo $block->getUrl('customfield/index/helpdesk') ?>" id="form_validate" method="POST">
            <div class="row">
              <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label class="control-label" for="yourname-field">Your name*</label>
                <input name="development_name" type="text" data-validate="{required:true}" class="form-control fc-name-icon" id="yourname-field" placeholder="matt henry">
              </div>
              <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label class="control-label" for="email-field">Email address*</label>
                <input name="email" type="email" data-validate="{required:true}" class="form-control fc-email-icon" id="email-field" placeholder="*********@gmail.com">
              </div>
            </div>

            <div class="row">
              <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label class="control-label" for="companyname-field">Company name</label>
                <input name="company_name" type="text" data-validate="{required:true}" class="form-control fc-company-icon" id="companyname-field" placeholder="matt henry">
              </div>
              <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label class="control-label" for="number-field">Your phone number*</label>
                <input name="phone_number" type="number" data-validate="{required:true}" class="form-control fc-phone-icon" id="number-field" placeholder="*******768">
              </div>
            </div>

            <div class="form-group">
              <label class="control-label" for="message-field">Let us about you*</label>
              <textarea name="message" class="form-control" data-validate="{required:true}" id="message-field" rows="6" placeholder="hii, there i would like...."></textarea>
            </div>

            <div class="text-center mt-4">
              <button type="submit" class="btn btn-primary">Submit</button>
              <p class="small-text">We'll get back to you in 1-2 business days.</p>
            </div>
          </form>

        </div>
      </div>



    </div>
  </section>

  
    </div>
  </div>
<script>
  require(['jquery'], function($) {
    $(document).ready(function() {
      $('.nav-link').on('click', function(event) {
        event.preventDefault(); // Prevent default behavior of the link
        
        // Remove 'active' class from all tab links
        $('.nav-link').removeClass('active');

        // Add 'active' class to the clicked tab link
        $(this).addClass('active');

        // Hide all tab panes
        $('.tab-pane').removeClass('show active');

        // Show the corresponding tab pane
        var targetId = $(this).attr('href');
        $(targetId).addClass('show active');
      });

      // Trigger click on first tab by default to show its content
      $('#ict-tab').trigger('click');
    });
  });
</script>




<script>
require(['jquery'], function($) {
   $(document).ready(function() {
        $('.faq-item .question').click(function() {
            var $faqItem = $(this).closest('.faq-item');
            var $answer = $faqItem.find('.answer');

            // Check if the clicked question is already active
            var isActive = $faqItem.hasClass('active');

            // Remove active class from all questions
            $('.faq-item').removeClass('active');

            // If the clicked question was not active, add active class
            if (!isActive) {
                $faqItem.addClass('active');
            }

            // Close all other answers
            $('.faq-item .answer').not($answer).slideUp();

            // Toggle display of clicked answer
            $answer.slideToggle();
        });
    });
});

</script>
<script>
      // Set the date we're counting down to
      var countDownDate = new Date("May 25, 2024 11:59:59").getTime();

      // Update the count down every 1 second
      var x = setInterval(function() {
        // Get today's date and time
        var now = new Date().getTime();
        // Find the distance between now and the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        // var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Output the result in an element with id="demo"
        // document.getElementById("day-demo").innerHTML = days;
        
        document.getElementById("hours-demo").innerHTML = hours;

        document.getElementById("minutes-demo").innerHTML = minutes;

        document.getElementById("seconds-demo").innerHTML = seconds;

        // If the count down is over, write some text 
        if (distance < 0) {
          clearInterval(x);
          document.getElementById("demo").innerHTML = "EXPIRED";
        }
      }, 1000);
    </script>
    <script>
  require([
    'jquery',
    'mage/validation'
], function ($) {
    $.validator.addMethod(
        'validate-custom-phone', 
        function (value, element) {
            // Check if the value matches the allowed format and has a maximum length of 10 digits
            return this.optional(element) || /^[0-9 ()+-]{10}$/.test(value);
        }, 
        $.mage.__('Please enter a valid 10-digit phone number.')
    );

    $('#form_validate').mage('validation', );{}

});
</script>
