<?php $helper = $this->helper('Itheavens\Fanpage\Helper\Data'); ?>
<!-- Mageleven? Solutions -->
<section class="magsolution">
   <div class="container">
      <div class="row">
         <div class="col-lg-12 wow fadeInDown">
            <h2><?= __('Mageleven? Solutions'); ?></h2>
         </div>
         <?php foreach(array_reverse($helper->getPages()) as $page) : ?>
         <div class="col-lg-3 col-md-6 wow fadeInUp">
            <div class="solbox">
               <?php if(!empty($page->getImage())) : ?>
               <div class="imgbox"><a href="<?= $block->getUrl($page->getIdentifier());?>"><img class="img-fluid" src="<?= $helper->getMediaUrl($page->getImage()); ?>" alt="<?= __($page->getTitle()); ?>"></a></div>
               <?php endif; ?>
               <h3><a href="<?= $block->getUrl($page->getIdentifier());?>"><?= __($page->getTitle()); ?></a></h3>
               <p><?= __($page->getCustomContent()); ?></p>
               <a class="btn btn-default" href="<?= $block->getUrl($page->getIdentifier());?>"><?= __('See More'); ?></a>
            </div>
         </div>
         <?php endforeach; ?>
      </div>
   </div>
</section>