
<meta name="author" content="Mageleven"/>
<meta content="Business" name="classification" />
<meta content="Global" name="distribution" />
<meta name="document-type" content="Public" />
<meta name="document-distribution" content="Global" />
<meta name="document-rating" content="Safe for Kids" />
<meta name="revisit-after" content="3 days" />
<meta name="geo.placename" content="Global" />
<meta name="rating" content="General" />
<meta name="audience" content="All" />

<meta property="og:site_name" content="Mageleven">
<meta property="og:locale" content="en_US">
<meta property="og:title" content="Magento 2 Extensions Services Provider Company - Mageleven">
<meta property="og:description" content="Transform your Magento 2 store with our cutting-edge extensions and expert services. Elevate performance, and enhance user experience. Choose Mageleven!">
<meta property="og:type" content="website">
<meta property="og:url" content="https://mageleven.com/">
<meta property="og:image" content="https://mageleven.com/static/frontend/Mageleven/m2-theme/en_US/images/logo.png">
<meta property="og:type" content="article" />

<meta property="twitter:card" content="summary" />
<meta property="twitter:title" content="Magento 2 Extensions Services Provider Company - Mageleven" />
<meta name="twitter:creator" content="@mageleven" />
<meta name="twitter:site" content="@mageleven" />
<meta property="twitter:description" content="Transform your Magento 2 store with our cutting-edge extensions and expert services. Elevate performance, and enhance user experience. Choose Mageleven!" />
<meta name="twitter:image" content="https://mageleven.com/static/frontend/Mageleven/m2-theme/en_US/images/logo.png" />
