<section class="service-banner">
   <div class="container">
      <div class="row">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-banner')->toHtml(); ?>
      </div>
   </div>
</section>
<section class="migration wow fadeInUp">
	<div class="container">
		<div class="row">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-to-magento-2')->toHtml(); ?>
		</div>
	</div>
</section>
<section class="imporveflex wow fadeInUp">
   <div class="container">
      <div class="row justify-content-center">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-improve-flexibility')->toHtml(); ?>
      </div>
   </div>
</section>
<section class="marketing wow fadeInUp">
   <div class="container">
      <div class="row">
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-marketing-and-technical')->toHtml(); ?>
      </div>
   </div>
</section>
<div class="replatform wow fadeInUp">
	<div class="container">
		<div class="row justify-content-between">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-replatform-with-aheadworks')->toHtml(); ?>
		</div>
	</div>
</div>
<div class="howwedo wow fadeInUp">
   <div class="container">
      <div class="row">
         <div class="col-lg-12 text-center">
            <h2>How we do it?</h2>
         </div>
      </div>
      <div id="accordionExampleMig" class="accordion">
         <div class="row justify-content-between">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-faqs')->toHtml(); ?>
         </div>
      </div>
   </div>
</div>
<div class="container">
   <div class="row justify-content-center">
      <div class="col-lg-10">
         <div class="howorange"> 
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('migration-faqs-bottom')->toHtml(); ?>
         </div>
      </div>
   </div>
</div>
