<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Mageleven - Magento 2 Extensions Services Provider Company",
  "legalName": "Mageleven",
  "url": "https://mageleven.com/",
  "logo": "https://mageleven.com/static/frontend/Mageleven/m2-theme/en_US/images/logo.png",
  "description": "Transform your Magento 2 store with our cutting-edge extensions and expert services. Elevate performance, and enhance user experience. Choose Mageleven!",
  "address": {
	"@type": "PostalAddress",
	"streetAddress": "30 N Gould St, STE R Sheridan, WY, 82801, USA",
	"addressLocality": "Sheridan",
	"addressRegion": "Wyoming",
	"postalCode": "82801",
	"addressCountry": "USA"
  },
  "contactPoint": {
	"@type": "ContactPoint",
	"telephone": "+1-205-525-9914",
	"contactType": "customer service"
  },
  "email": "info@mageleven.com",
  "sameAs": [
	"https://www.facebook.com/mageleven",
	"https://twitter.com/mage11official",
	"https://www.linkedin.com/company/mageleven-official"
    
  ]
}
</script>
