<section class="service-banner">
	<!-- <div class="container">
		<div class="row"> -->
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-banner')->toHtml(); ?>
		<!-- </div>
	</div> -->
</section>
<section class="devservices wow fadeInUp">
	<!-- <div class="container">
		<div class="row"> -->
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-development')->toHtml(); ?>
		<!-- </div>
	</div> -->
</section>
<section class="magento-service wow fadeInUp">
   <!-- <div class="container">
      <div class="row"> -->
         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-our-services')->toHtml(); ?>
      <!-- </div>
   </div> -->
</section>
<!-- letstalk -->
<section class="letstalk">
   <!-- <div class="container">
      <div class="row"> -->
         <div class="col-lg-12">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-lets-talk')->toHtml(); ?>
         </div>
      <!-- </div>
   </div> -->
</section>
<section class="expertise">
   <!-- <div class="container">
      <div class="row"> -->
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-expertise')->toHtml(); ?> 
      <!-- </div>
   </div> -->
</section>
 