<!-- banner -->
<section class="page-title-sec">
  <div class="container">
    <div class="page-title">Sitemap</div>
  </div>
</section>

<section class="sitemap-page">
  <div class="container">
    
    <!-- Row Start -->
    <div class="row bottom-gape">
      <div class="col-xl-3 col-lg-4">
        <div class="sitemap-title-box">
          <span>Services</span>
        </div>
      </div>
      <div class="col-xl-9 col-lg-8">
        <div class="sitemap-listing">
          <a href="#" class="sitemap-list sitemap-lightY"><span>Custom Development</span></a>
          <a href="#" class="sitemap-list sitemap-darkG"><span>MagentoMaintenance Services</span></a>
          <a href="#" class="sitemap-list sitemap-lightG"><span>Upgrade to Magento 2</span></a>
          <a href="#" class="sitemap-list"><span>B2B Implementation</span></a>
          <a href="#" class="sitemap-list sitemap-darkHG"><span>Performance Optimization Service</span></a>
          <a href="#" class="sitemap-list sitemap-darkG"><span>Magento SEO</span></a>
          <a href="#" class="sitemap-list sitemap-primaryH"><span>Support</span></a>
          <a href="#" class="sitemap-list sitemap-red"><span>Magento Migration</span></a>
        </div>
      </div>
    </div>
    <!-- Row Start -->
    
    <!-- Row Start -->
    <div class="row">
      <div class="col-xl-3 col-lg-4">
        <div class="sitemap-title-box primary-bg">
          <span>Customer Service</span>
        </div>
      </div>
      <div class="col-xl-9 col-lg-8">
        <div class="sitemap-listing">
          <a href="#" class="sitemap-list sitemap-lightY"><span>About Us</span></a>
          <a href="#" class="sitemap-list sitemap-darkG"><span>Partner Program</span></a>
          <a href="#" class="sitemap-list sitemap-lightG"><span>Discount Program</span></a>
          <a href="#" class="sitemap-list"><span>Liences Agrenment</span></a>
          <a href="#" class="sitemap-list sitemap-darkHG"><span>Become a contributor</span></a>
          <a href="#" class="sitemap-list sitemap-darkG"><span>Contact Us</span></a>
          <a href="#" class="sitemap-list sitemap-red"><span>Reward Program</span></a>
        </div>
      </div>
    </div>
    <!-- Row Start -->

  </div>
</section>


<div class="stay-div">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-xl-7 col-lg-7">
        <div class="stay-div-title">Stay Updated and Save Big!</div>
        <p>Unlock exclusive deals on the latest innovations from Mageleven</p>
      </div>
      <div class="col-xl-5 col-lg-5">
    <form action="<?php echo $block->getUrl('customfield/index/sitemap') ?>" method="POST" id="Contactform">
  <div class="form-group">
    <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your email address" required>
  </div>
  <button type="submit" class="btn primary-border">
    Send
    <svg width="21" height="16" viewBox="0 0 21 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M4.79847 15.9565L3.01973 10.2262L10.0672 5.94451L1.83391 6.40606L0.0551758 0.675781L20.5727 2.68349L4.79847 15.9565Z" fill="#EBEBEB"></path>
    </svg>
  </button>
</form>
      </div>
    </div>
  </div>
</div>
<script>
  require([
    'jquery',
    'mage/validation'
], function ($)
 {
    $.validator.addMethod(
        'validate-custom-phone', 
        function (value, element) {
            // Check if the value matches the allowed format and has a maximum length of 10 digits
            return this.optional(element) || /^[0-9 ()+-]{10}$/.test(value);
        }, 
        $.mage.__('Please enter a valid 10-digit phone number.')
    );

    $('#Contactform').mage('validation', {});

});
</script>





</div>
</div>






