<section class="user-guid-banner">
    <div class="container">
      <div class="row align-items-end">
        <div class="col-xl-6 col-lg-6">
          <div class="fn44">Magento 2 Peace of Mind: Make a Secure Choice for Extensions, Customization, and Storefronts</div>
        </div>

        <div class="col-xl-6 col-lg-6">
          <img src="<?php echo $this->getUrl('media/cms/new')."user-guide-banner-img.png"; ?>" alt="user-guide-banner">
        </div>

      </div>
    </div>
  </section>

  <section class="company-main-info">
    <div class="container">
      <div class="section-title">Let's unleash your eCommerce potential with</div>
      <div class="row">

        <!-- Col Start -->
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xs-6">
          <div class="company-info-list">
            <img src="<?php echo $this->getUrl('media/cms/new')."slack-icon.png"; ?>" alt="slack-icon">
            <div class="company-info-text">Unmatched Expertise</div>
          </div>
        </div>
        <!-- Col End -->
        
        <!-- Col Start -->
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xs-6">
          <div class="company-info-list">
            <img src="<?php echo $this->getUrl('media/cms/new')."userguide12.png"; ?>" alt="Pixel-Perfect-support">
            <div class="company-info-text">Pixel-Perfect Design</div>
          </div>
        </div>
        <!-- Col End -->

        
        <!-- Col Start -->
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xs-6">
          <div class="company-info-list">
          <img src="<?php echo $this->getUrl('media/cms/new')."fast-forward.png"; ?>" alt="fast-forward">
            <div class="company-info-text">Future-Proof Performance</div>
          </div>
        </div>
        <!-- Col End -->
         <!-- Col Start -->
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xs-6">
          <div class="company-info-list">
            <img src="<?php echo $this->getUrl('media/cms/new')."personal-support.png"; ?>" alt="personal-support">
            <div class="company-info-text">Dedicated Support</div>
          </div>
        </div>
        <!-- Col End -->
      </div>
    </div>
  </section>

  <section class="guide-main-div">
    <div class="container">
      <div class="row">

           <div class="col-xl-3 col-lg-4">
        <div class="blog-category user-guide-sprite nav" id="myTab" role="tablist">
          <!-- 1 -->
          <a class="blog-category-link nav-link active" id="license-tab" data-toggle="tab" href="#license" role="tab" aria-controls="license" aria-selected="true">
            <div class="blog-category-icon guide-tabs-icon"></div>
            <span>License</span>
          </a>
          <!-- 1 End -->

          <!-- 2 -->
          <a class="blog-category-link nav-link" id="updates-tab" data-toggle="tab" href="#updates" role="tab" aria-controls="updates" aria-selected="false">
            <div class="blog-category-icon guide-tabs-icon updates-guide"></div>
            <span>Update</span>
          </a>
          <!-- 2 End -->

          <!-- 3 -->
          <a class="blog-category-link nav-link" id="subscription-tab" data-toggle="tab" href="#subscription" role="tab" aria-controls="subscription" aria-selected="false">
            <div class="blog-category-icon guide-tabs-icon subscription-guide"></div>
            <span>Subscription</span>
          </a>
           <!-- 4 -->
          <a class="blog-category-link nav-link active" id="refund-tab" data-toggle="tab" href="#refund" role="tab" aria-controls="license" aria-selected="true">
            <div class="blog-category-icon guide-tabs-icon"></div>
            <span>Refund</span>
          </a>
           <!-- 5 -->
          <a class="blog-category-link nav-link active" id="compatibilities-tab" data-toggle="tab" href="#compatibilities" role="tab" aria-controls="license" aria-selected="true">
            <div class="blog-category-icon guide-tabs-icon"></div>
            <span>Compatibilities</span>
          </a>
           <!-- 6 -->
          <a class="blog-category-link nav-link active" id="support-tab" data-toggle="tab" href="#support" role="tab" aria-controls="license" aria-selected="true">
            <div class="blog-category-icon guide-tabs-icon"></div>
            <span>Support</span>
          </a>
        </div>
      </div>

      <div class="col-xl-9 col-lg-8">
        <div class="tab-content" id="myTabContent">
          <!-- 1 -->
          <div class="tab-pane fade show active" id="license" role="tabpanel" aria-labelledby="license-tab">
            <h2> Extensions </h2>
            <ul class="ul-check">
              <li>Non-exclusive, revocable, non-transferable license</li>
              <li>Use extensions for a single Magento 2 store</li>
              <li>Access updates for a specified duration (check license agreement)</li>
              <li>May require a subscription for ongoing updates and support</li>
            </ul>
             <h2> Website Development </h2>
            <ul class="ul-check">
              <li>License for use granted, but intellectual property rights retained by Mageleven</li>
              <li>Specific terms agreed upon in the development project agreement</li>
              <li>May include a subscription plan for ongoing support and maintenance</li>
            </ul>
             <h2> Key takeaways </h2>
            <ul class="ul-check">
              <li>Mageleven retains ownership of its intellectual property.</li>
              <li>Permissions and restrictions vary based on the type of service.</li>
              <li>Always refer to the specific license agreement for full details.</li>
            </ul>
          </div>
 <!-- 2 -->
          <div class="tab-pane fade" id="updates" role="tabpanel" aria-labelledby="updates-tab">
            <p> Staying Ahead with Mageleven: Updates to Supercharge Your E-commerce
Experience continuous improvement with these key updates on Mageleven services:</p>
            <ul class="ul-check">
              <li><strong>Regular Extension Enhancements:</strong> Get fresh features, improved performance, and bug fixes for your extensions, keeping your store optimized.</li>
              <li><strong>Secure Upgrades:</strong> Maintain peace of mind with access to security patches and updates, ensuring your online store stays protected.</li>
              <li><strong>Transparent Roadmap:</strong> See what's planned! We share our update pipeline to help you anticipate future features and plan accordingly.</li>
              <li><strong>Subscription Options:</strong> Choose the update plan that fits your needs, ensuring ongoing access to the latest advancements.</li>
              <li><strong>Dedicated Support:</strong> Have questions or need help applying updates? Our friendly team is always happy to assist.</li>
            </ul>
            <p>Updates ensure your E-commerce journey with Mageleven stays dynamic and rewarding.</p>
          </div>
 <!-- 3 -->
          <div class="tab-pane fade" id="subscription" role="tabpanel" aria-labelledby="subscription-tab">
            <p>Scale Your Success with Mageleven Subscriptions</p>
            <ul class="ul-check">
              <li><strong>Extension Subscriptions:</strong> Stay future-proof with ongoing access to updates, support, and new features for your chosen extensions.</li>
              <li><strong>Website Development Subscriptions:</strong> Ensure top-notch performance and security with dedicated support, maintenance, and updates for your custom Magento website</li>
              <li><strong>Flexible Options:</strong> Choose from monthly or annual plans to match your business needs and budget.</li>
              <li><strong>Peace of Mind:</strong> Prioritize stability and growth by leaving updates and maintenance to the experts.</li>
                <li><strong>Dedicated Contact:</strong> Access a dedicated support team for prompt and personalized assistance.</li>
            </ul>
            <p>Invest in Mageleven subscriptions and focus on what matters most – growing your E-commerce empire.</p>
          </div>
          <!-- 4 -->
          <div class="tab-pane fade" id="refund" role="tabpanel" aria-labelledby="refund-tab">
            <p>Refund Assurance: We stand behind our work with a transparent, worry-free policy:
We offer a transparent, worry-free refund assurance policy and a variety of bonus benefits to ensure your satisfaction. We stand behind our work and are confident that you will be happy with the results.</p>
            <ul class="ul-check">
              <li><strong>100% Satisfaction Guarantee:</strong> Within 30 days of purchase, if our extensions do not exceed your expectations, simply request a full refund. No questions asked.</li>
              <li><strong>Custom Project Flexibility:</strong> Our project agreements clearly outline refund terms based on agreed-upon deliverables. If we miss the mark, adjustments or compensation are available.</li>
              <li><strong>Transparent Communication:</strong> Throughout every step, we maintain open communication, ensuring you're fully informed and confident in your investment.</li>
            </ul>
            <h2>Bonus Benefits</h2>
            <ul class="ul-check">
              <li><strong>Free Consultations:</strong> Discuss your goals and get expert advice before committing.</li>
              <li><strong>Guaranteed Uptime:</strong> Rest assured, your online store stays up and running, driving sales 24/7.</li>
                <li><strong>Open Source Champions:</strong> We actively contribute to the Magento community, ensuring long-term stability and support.</li>
            </ul>
          </div>
          <!-- 5 -->
          <div class="tab-pane fade" id="compatibilities" role="tabpanel" aria-labelledby="compatibilities-tab">
            <p>Seamless Integration, Effortless Experience</p>
            <ul class="ul-check">
              <li><strong>Compatibility Focus:</strong> Mageleven meticulously designs extensions and websites to seamlessly integrate with various Magento 2 configurations.</li>
              <li><strong>User Responsibility:</strong> While we strive for extensive compatibility, we encourage users to verify compatibility before purchase to ensure optimal performance.</li>
              <li><strong>Assessment Factors:</strong> Compatibility depends on factors like the Magento version, hosting provider, installed modules, and customizations.</li>
                <li><strong>Expert Guidance:</strong> Unsure about compatibility? Our team is always ready to assist! We'll help determine the perfect fit for your unique setup.</li>
            </ul>
            <p>Contact us for personalized compatibility assessments and ensure a smooth e-commerce journey.</p>
          </div>
          <!-- 6 -->
          <div class="tab-pane fade" id="support" role="tabpanel" aria-labelledby="support-tab">
            <p>Support for custom Magento websites is outlined in the project agreement. Mageleven reserves the right to change its support policies at any time. Customers are responsible for keeping their Magento websites up to date. Mageleven is not responsible for damages caused by a customer's failure to keep their Magento website up to date.</p>
            <ul class="ul-check">
              <li><strong>Dedicated Extension Support:</strong> Get 12 months of post-purchase assistance with installation, configuration, and bug fixes for your chosen extensions.</li>
              <li><strong>Website Development Care:</strong> Enjoy comprehensive maintenance and security updates for your custom Magento website through dedicated support plans.</li>
              <li><strong>Responsive Customer Focus:</strong> Reach our friendly and knowledgeable team via email or phone for prompt and personalized assistance with any inquiries.</li>
              <li><strong>Proactive Solution-finding:</strong> We actively monitor your extensions and website to identify potential issues and address them before they impact your e-commerce experience.</li>
              <li><strong>Community-driven Knowledge Base:</strong> Access a wealth of helpful resources, tutorials, and FAQs to empower self-resolution and ongoing learning.</li>
                <li><strong>Investment in Your Success:</strong> Our support goes beyond technical assistance; we're here to help you optimize your ecommerce journey and achieve your business goals.</li>
            </ul>
          </div>

          <a href="<?= $block->getUrl('terms-and-conditions'); ?>" class="btn btn-primary btn-sm">Access all document</a>
        </div>
      </div>

    </div>
  </div>
</section>

  <section class="our-policies-section">
    <div class="container">
      <div class="section-title">Mageleven’s Privacy Policy</div>
      <p>Mageleven takes data privacy seriously. They collect minimal user information like usernames, contact details, and IP addresses. This data is used to improve services, send promotional emails (with an unsubscribe option), and personalize the website. Mageleven uses cookies to analyze traffic and tailor the experience, but these cookies don't access personal information. Users can control cookies through browser settings, but disabling them may affect website functionality. Mageleven updates this policy as needed, so check back periodically.</p>

      <a href="<?= $block->getUrl('privacy-policy'); ?>" class="btn btn-primary btn-sm">read more</a>
    </div>
  </section>
<!-- section start -->
  <section class="seller-extensions-sec">
    <div class="container">
      <div class="section-title">Our best seller extensions</div>

    </div>
  </section>
<!-- end -->
  </div>
  </div>

  <!-- <script>
  require(['jquery'],function($){
  $(document).ready(function() {
     $('.tab-pane').not(':first').hide();
    // Adding click event listeners to the tab links
    $('.nav-link').on('click', function(event) {
        event.preventDefault(); // Prevent default behavior of the link

        // Hide all paragraphs
        $('.tab-pane').hide();

        // Show the corresponding paragraph
        var targetId = $(this).attr('href');
        $(targetId).show();
    });
});

  });
</script> -->
<!-- <script>
  require(['jquery'],function($){
setTimeout(function(){

  $('.build-bundle-slider').owlCarousel({
        items: 1,
        autoplay: true,
        autoHeight: true,
        nav: true,
        dots: false,
        loop: true,
        smartSpeed: 450,
        navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"],
        responsiveClass:true,
        responsive:{
          0:{
            items:5
          }
        }
      });
},3000);
})
</script> -->
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.nav-link').on('click', function(event) {
                event.preventDefault(); // Prevent default behavior of the link

                // Remove 'active' class from all tab links
                $('.nav-link').removeClass('active');

                // Remove 'active' class from all tab content
                $('.tab-pane').removeClass('active show');

                // Add 'active' class to the clicked tab link
                $(this).addClass('active');

                // Show the corresponding tab pane
                var targetId = $(this).attr('href');
                $(targetId).addClass('active show');
            });

            // Trigger click on first tab by default to show its content
            $('#license-tab').trigger('click');
        });
    });
</script>