<?php  
$testimonials = $this->getCollection(); 
if($testimonials && count($testimonials)) :
	$mediaUrl = $this->getMediabaseUrl();
?>
<div class="owl-carousel testimonial-carousel">
<?php foreach ($testimonials as $testimonial): ?> 
	<div class="item">
		<h2><?= __($testimonial->getData('name')); ?></h2>
		<p><?= __($testimonial->getData('text')); ?></p>
		<img src="<?= $mediaUrl . $testimonial->getData('image'); ?>" alt="<?= __($testimonial->getData('name')); ?>"/>
		<h4><?= __($testimonial->getData('clientname')); ?></h4>
      <h5><?= __($testimonial->getData('job')) ; ?></h5>
	</div>
<?php endforeach; ?>
</div>
<!-- <script>
   require([
      'jquery',
      'owlCarousel',
      'domReady!'
   ], function ($) {
      'use strict';
      $.noConflict();
      $(".testimonial-carousel").owlCarousel({
         items: 4,
         autoplay: true,
         margin: 30,
         nav: true,
         dots: false,
         loop: true,
         smartSpeed: 450,
         navText: ["<i class='fa fa-chevron-left'></i>", "<i class='fa fa-chevron-right'></i>"],
         responsiveClass: true,
         responsive: {
            0: {
               items: 1
            }
         }
      });
   });
</script> -->
<?php endif; ?>