<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (sizeof($block->getTerms()) > 0): ?>
    <ul>
        <?php foreach ($block->getTerms() as $_term): ?>
            <li>
                <a href="<?= /* @escapeNotVerified */ $block->getSearchUrl($_term) ?>">
                    <?= $block->escapeHtml($_term->getQueryText()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="message notice">
        <div><?= /* @escapeNotVerified */ __('There are no search terms available.') ?></div>
    </div>
<?php endif; ?>
