<?php
/**
 * Copyright © Mageleven (support@mageleven.com). All rights reserved.
 * Please visit Mageleven.com for license details (https://mageleven.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Mageleven\HtmlSitemap\Block\Additional\Additional $block
 */

$links = $block->getLinksArray();
?>

<?php if (count($links)): ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2 class="sitemap-title"><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <div class="sitemap-item-wrap">
            <?php foreach ($links as $link): ?>
            <?php if ($link): ?>
                <a class="sitemap-item" href="<?= $block->escapeUrl($block->getBaseUrl() . $link['url'])?>" title="<?= $block->escapeHtml($link['title'])?>">
                    <?= $block->escapeHtml($link['title'])?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
        <?php if ($block->showViewMore()): ?>
            <a class="view-more" href="<?= $block->escapeUrl($block->getUrl('*/additional/links'))?>">
                <?= $block->escapeHtml(__('View more'))?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>
