<?php
/**
 * Copyright © Mageleven (support@mageleven.com). All rights reserved.
 * Please visit Mageleven.com for license details (https://mageleven.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Mageleven\HtmlSitemap\Block\Blog\Category $block
 */

$items = $block->getGroupedChildes();
?>

<?php if (count($items)) { ?>
    <div class="sitemap-item-type sitemap-item-section">
        <h2><?= $block->escapeHtml(__($block->getBlockTitle())) ?></h2>
        <div class="widget block block-categories" data-bind="scope: 'categories'">
            <div class="accordion"  id="accordion-2">
                <?php
                $level = -1;
                $first = true;
                foreach ($items as $item) {
                    $newLevel = $item->getLevel();
                    if ($level == $newLevel && !$first) {
                         echo '</li>';
                    }
                    if ($level < $newLevel) {
                        echo '<ul>';
                    }
                    if ($level > $newLevel) {
                        for ($i = $level; $i > $newLevel; $i--) {
                            echo '</ul></li>';
                        }
                    } ?>
                    <li>
                    <a href="<?= $block->escapeUrl($item->getUrl()) ?>" title="<?= $block->escapeHtml($block->escapeHtml($item->getTitle())) ?>">
                        <?= $block->escapeHtml($block->escapeHtml($item->getTitle())) ?>
                    </a>
                    <?php
                    $level = $newLevel;
                    $first = false;
                }

                $closedTags = ($level > 0) ? $level - 1 : 1;
                echo str_repeat('</li></ul>', $closedTags);

                ?>
            </div>
            <?php if ($block->showViewMore()): ?>
                <a class="view-more" href="<?= $block->escapeUrl($block->getUrl('*/blog_category/categories'))?>">
                    <?= $block->escapeHtml(__('View more'))?>
                </a>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>
