<?php
/** @var \Magento\Catalog\Model\Product $currentProduct */
$currentProduct = $block->getCurrentProduct();
?>

<a href="<?php echo $currentProduct->getBackendDemo(); ?>" class="btn btn-primary" id="backend-demo">
    <i class="fas fa-desktop"></i> Backend Demo
</a>

<a href="<?php echo $currentProduct->getFrontendDemo();?>" class="btn btn-primary" id="frontend-demo">
    <i class="fas fa-desktop"></i> Frontend Demo
</a>
<!-- User Input -->
<div class="backfrontdemo">
<div style="margin-bottom: 10px;">
    <label for="SQDQOP8" style="display: inline-block;">Username:</label>
    <span style="display: inline-block;">
    <div class="input-group">
        <input class="admin__control-text" type="text" style="width: 160px;" name="product[username]" aria-describedby="notice-SQDQOP8" id="SQDQOP8" maxlength="255" value="<?php echo $currentProduct->getData('username'); ?>">
    </div>
    </span>
</div>

<!-- Password Input -->
<!-- Password Input -->
<div style="margin-bottom: 10px; position: relative;">
    <label for="BTC1ESL" style="display: inline-block;">Password:</label>
    <span style="display: inline-block;">
        <div class="input-group">
            <input class="admin__control-text" type="password" style="width: 150px;" name="product[password]" aria-describedby="notice-BTC1ESL" id="BTC1ESL" maxlength="255" value="<?php echo $currentProduct->getData('password'); ?>"/>
            <div class="input-group-append" style="position: absolute; top: 0; right: 0; bottom: 0;">
                <i class="fas fa-eye" id="toggle-password" style="color: black; height: 100%; background: #8080805c; display: flex; font-size: 20px;"></i>
            </div>
        </div>
    </span>
</div>
</div>

<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var passwordVisible = false;

            // Toggle Password Visibility
            $(document).on('click', '#toggle-password', function () {
                var passwordInput = $('#BTC1ESL');
                var icon = $(this);

                passwordVisible = !passwordVisible;

                if (passwordVisible) {
                    passwordInput.prop('type', 'text');
                    icon.removeClass('fas fa-eye').addClass('fas fa-eye-slash');
                } else {
                    passwordInput.prop('type', 'password');
                    icon.removeClass('fas fa-eye-slash').addClass('fas fa-eye');
                }
            });
        });
    });
</script>
