<!-- banner -->
<section class="service-banner careers-banner">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 wow fadeInUp">
				<div class="slidcontent text-center">
					<h1 class="upcase">How can we help?</h1>
					<!-- <div class="search">
						<div class="input-group">
						  <input type="text" class="form-control" placeholder="Ask a Question" aria-label="Recipient's username" aria-describedby="button-addon2">
						  <div class="input-group-append">
						    <button class="btn btn-primary" type="button" id="button-addon2">Search</button>
						  </div>
						</div>
					</div>	 -->					
					<p>Popular help topics: <span>create coupon codes, remarketing, smtp timed out, <br>one step checkout extension error</span></p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- careers mid -->
<section class="jointeam">
	<div class="container">
		<div class="row">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('career-join-team')->toHtml(); ?>
		</div>
	</div>
</section>
<!-- Choose Your Post -->
    <div class="choosepost">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-12">
    				<h2>Choose Your Post</h2>
    			</div>
    		</div>
    		<div class="row">
    			<?php $allcareer = $this->getListCareer() ?>
				<?php if($allcareer && count($allcareer) > 0): ?>
					<?php foreach($allcareer as $career): ?>
		    			<div class="col-md-6">
		    				<div class="postbox">
		    					<?php 
		    						if($career->getData('image')){
		    							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						                $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
						                $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
						                $name = $career->getData('image');
						         ?>
		    					<div class="imgbox">
		    						<img src="<?php echo $mediaUrl.'imageUploader/images/'.$name; ?>" class="img-fluid" alt="">
		    					</div>
		    					<?php } ?>
		    					<div class="content">
		    						<h3>
		    							<a href="<?php echo $block->getBaseUrl() ?>career/index/view/?id=<?php echo $career->getId() ?>">
											<?php echo $career->getTitle() ?>
										</a>
									</h3>
			    					<?php if(strlen($career->getDescription())>322){ 
			    						echo substr($career->getDescription(),0, 322);
			    					} else {
			    						echo $career->getDescription();
			    					} ?>
			    					<div class="col-xs-12 center-block text-center">
				    					<a href="<?php echo $block->getBaseUrl() ?>career/index/view/?id=<?php echo $career->getId() ?>" class="btn btn-primary">Apply For The Post</a>
				    				</div>
			    				</div>
		    				</div>
		    			</div>
		    		<?php endforeach; ?>
					<div class="col-md-12">
					<?php if($this->getPagerHtml()): ?>
						<?php echo $this->getPagerHtml(); ?>
					<?php endif; ?>
					</div>
				<?php else: ?>
					<div class="col-md-12">
	    				<div class="postbox">
							<div class="mageleven-no-records">
								<?php echo __('Career not available'); ?>
							</div>
						</div>
					</div>
				<?php endif; ?>	
    		</div>
    	</div>
    </div>
<!-- join our team -->
<div class="joinourteam">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('career-join-our-team')->toHtml(); ?>	
			</div>
		</div>
	</div>
</div>
